import { LitElement, html } from 'https://unpkg.com/lit-element?module';

/** import('./typings/Greeting').Greeting Greeting */

/**
 * This file is generated by [web-component-analyzer](https://github.com/runem/web-component-analyzer) and is intended to illustrate [issue 152 from that repo](https://github.com/runem/web-component-analyzer/issues/152).
 *
 * To re-generate this file, run `npm run analyze`. The desired behavior is that the `greeting` prop below should reflect the data in [`typings/Greeting.ts`](typings/Greeting.ts).
 *
 * @element demo-element
 * @attr greeting {Greeting} - Who should we greet?
 */
class DemoElement extends LitElement {
  static properties = {
    greeting: { type: String, reflect: true }
  }

  constructor() {
    super();

    /** @type {Greeting} */
    this.greeting = '';
  }

  connectedCallback() {
    return html`<h1>Hello ${this.greeting}</h1>`;
  }
}

customElements.define('demo-element', DemoElement);
